### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [srepmub/tacovr#2]
Hello!

I found this project from https://hackaday.com/2022/11/18/diy-robotic-platform-aims-to-solve-walking-in-vr/

I don't see any code or design files in this repository. I hope you will upload them :)

Request for future: could you please add information about the license of this repository — is it allowed to copy, change and use the code, design files and images in any purpose?
It would be great to see any popular open source license.

**Comment by srepmub** [comment]
hi, and thanks! :)

I added a LICENSE. the embedded code is contained in the .ino file (for arduino). design files for the 3d printed parts are on thingiverse (as linked in the main page). all the infento parts are also listed. no real further design files needed at this point. I may add build intructions (or make a build video) at some point, but I think the design has to be improved first so actual walking is possible :P

so yeah the intention for this is to be a proper open source project. I'm open to further suggestions on how to improve!

**Comment by vazhnov** [comment]
GPL v3 — great! Thank you!
